image: golang:latest

format:
  stage: test
  script:
    - make format-tools
    - make format

lint:
  stage: test
  script:
    - make lint-tools
    - make lint

test:
  stage: test
  script: make test
