image: golang:latest

format:
  stage: test
  script:
    - make format-tools
    - make format

lint:
  image: mozgiii/gometalinter-docker:v2
  stage: test
  script: gometalinter --config=metalinter.config ./...

test:
  stage: test
  script: make test
