image: golang:latest

format:
  stage: test
  script:
    - make format-tools
    - make format

lint:
  image: mozgiii/gometalinter-docker:v2
  stage: test
  script:
    - GO111MODULE=on go mod vendor
    - GO111MODULE=off gometalinter --vendor --config=metalinter.config ./...

test:
  stage: test
  script: make test
