version: 2
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.23.8-alpine
    steps:
      - checkout
      - run: golangci-lint run
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: go-modules-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - run: make test
  verify-version:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: go-modules-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - run: make check-version
workflows:
  version: 2
  pipeline:
    jobs:
      - lint
      - test
      - verify-version:
          filters:
            branches:
              only:
                - /release/v[0-9]*\.[0-9]*\.[0-9]*/
